spring:
  application:
    name: berlin-clock-api
  mvc:
    apiversion:
      default-version: 1.0
      use:
        header: X-Api-Version
      supported-versions:
        - 1.0
        - 2.0


server:
  port: 8088